// Menentukan versi dari protobuf yang digunakan
syntax = "proto3";

// Mendefinisikan namespace atau modul untuk file ini
package user;

// Opsi untuk menentukan path dan nama package Go yang dihasilkan
// go_package harus sesuai dengan struktur folder project Go-mu

option go_package = "pb/user;userpb";


service UserService {
  rpc GetUser(UserRequest) returns (UserResponse);
   rpc ListUsers(Empty) returns (stream UserResponse); // << new
}

message UserRequest {
  int32 id = 1;
}

message UserResponse {
  string name = 1;
  int32 age = 2;
}

message Empty {} // << Tambahkan untuk request kosong

